# general settings
name: train_GSTSR_belly_x4
model_type: SwinIRModel
scale: 4
num_gpu: 1
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: belly
    type: PairedImageDataset
    dataroot_gt: /home/zhiyi/data/medical/belly/hr_sub
    dataroot_lq: /home/zhiyi/data/medical/belly/x4_sub
    meta_info_file: /home/zhiyi/pycharm-tmp/basicsr/basicsr/data/meta_info/meta_info_belly_GT.txt
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 96
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: belly_valid
    type: PairedImageDataset
    dataroot_gt: /home/zhiyi/data/medical/belly/hr_valid
    dataroot_lq: /home/zhiyi/data/medical/belly/x4_valid
    # filename_tmpl: '{}x2'
    io_backend:
      type: disk

# network structures
network_g:
  type: GSTSR
  upscale: 4
  in_chans: 3
  img_size: 48
  window_size: 8
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'
  scam: True
  gffm: True

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 100000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
